project_name: "Neocis_Assessment"

data:
  image_meta_path: "/home/mmandlem/Neocis_assessment/Image_data/image_data_info.csv"
  val_split: 0.2
  class_list: ["2.0 mm x 26 mm", "2.0 mm x 28 mm", "2.8 mm x 22 mm", "3.5 mm x 19 mm", "3.5 mm x 22 mm", "3.5 mm x 28 mm", "3.5 mm x 30 mm", "4.2 mm x 22 mm", "4.2 mm x 30 mm"]
  n_classes: 9
  n_workers: 16
  crop:
    top: 300
    left: 300
    height: 300
    width: 300

model:
  name: "drillbit_classification"
  exp_version: v005
  exp_tags:
    - 1280,512,512,9
    - augmentations for train and valid
    - image cropped 300x300
    - base model finetuning
  base_model: "mobilenet_v2"
  pretrained: True
  finetune: True

train:
  batch_size: 64
  epochs: 200
  base_lr: 0.00001
  max_lr: 0.001
  class_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  shuffle: True

early_stopping:
  tolerance: 100
  min_delta: 0


misc:
  clearml_api_path: "/home/mmandlem/Neocis_assessment/.clearml_config.yaml"
  checkpoint_path: "/home/mmandlem/Neocis_assessment/training_ckpts"


